// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8_RgipZOZhgNQjC6jJq2AuTfg0hZobw',
    appId: '1:863941088727:web:1046c91b72bf061a3f2792',
    messagingSenderId: '863941088727',
    projectId: 'messageme-7c3cc',
    authDomain: 'messageme-7c3cc.firebaseapp.com',
    storageBucket: 'messageme-7c3cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VYFNIZzAs6Lmcq_LtIkm4QahnyPuTMY',
    appId: '1:863941088727:android:6e308210c8aedfd73f2792',
    messagingSenderId: '863941088727',
    projectId: 'messageme-7c3cc',
    storageBucket: 'messageme-7c3cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3akIXaho2tX9fYZhtktwCvbk6JC7D1Xw',
    appId: '1:863941088727:ios:e9ca418a02967d6b3f2792',
    messagingSenderId: '863941088727',
    projectId: 'messageme-7c3cc',
    storageBucket: 'messageme-7c3cc.firebasestorage.app',
    iosBundleId: 'com.example.messageMe',
  );
}
